baseURL = "https://blog.leeminwoo.dev/"
languageCode = "en-us"
theme = "anatole"

[params]
title = "Minwoo Lee"
author = "Minwoo Lee"
enableMediumZoom = false
description = """
Developer
C, C++, Python, Go, Rust, Linux, Yocto
Mainly works in automotive industry
"""
profilePicture = "profile-image/profile.jpg"
mainSections = "post"
disableThemeSwitcher = true
readMore = true
contentratio = 0.65
pygmentsCodeFences = true
pygmentsUseClasses = true
customCss = ["css/syntax.css"]

[params.math]
enable = false
use = "katex"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/85minwoolee"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/vical1024"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:vical1024@gmail.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"