baseURL = "http://blog.leeminwoo.dev/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "anatole"


[params]
title = "Minwoo Lee"
author = "Minwoo Lee"
description = "Minwoo Lee(description)"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/85minwoolee"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/vical1024"


[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:vical1024@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"